# Generated by Django 6.0.4 on 2026-07-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='feedback',
        ),
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(default='no description', upload_to='notes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='topic',
            field=models.CharField(default='', max_length=200),
        ),
    ]
