import { useEffect, useMemo, useState } from "react";
import { FaUniversity, FaBook, FaLayerGroup, FaUsers, FaCalendarAlt, FaClock } from "react-icons/fa";
import { classApi } from "../services/classApi";
import "../styles/AttendanceHeader.css";
import "../styles/AttendanceControls.css";

const unique = (items) => [...new Set(items.filter((item) => item !== undefined && item !== null && item !== ""))];

function AttendanceHeader({ attendanceInfo, onLoadStudents, onNotHeld }) {
  const [sessions, setSessions] = useState([]), [course, setCourse] = useState(""), [semester, setSemester] = useState(""), [section, setSection] = useState(""), [subject, setSubject] = useState("");
  const [date, setDate] = useState(new Date().toISOString().split("T")[0]), [startTime, setStartTime] = useState(""), [endTime, setEndTime] = useState(""), [classSessionId, setClassSessionId] = useState("");
  useEffect(() => { classApi.list().then(setSessions).catch(() => setSessions([])); }, []);
  useEffect(() => { if (!attendanceInfo) return; setCourse(attendanceInfo.course || attendanceInfo.course_name || ""); setSemester(attendanceInfo.semester || ""); setSection(attendanceInfo.section || ""); setSubject(attendanceInfo.subject_name || attendanceInfo.subject || ""); setDate(attendanceInfo.date || new Date().toISOString().split("T")[0]); setStartTime(attendanceInfo.time || attendanceInfo.start_time || ""); setEndTime(attendanceInfo.endTime || attendanceInfo.end_time || ""); setClassSessionId(attendanceInfo.classSessionId || attendanceInfo.id || ""); }, [attendanceInfo]);
  const courseSessions = useMemo(() => sessions.filter((item) => String(item.course_name || item.course) === String(course)), [sessions, course]);
  const semesterSessions = useMemo(() => courseSessions.filter((item) => !semester || String(item.semester) === String(semester)), [courseSessions, semester]);
  const sectionSessions = useMemo(() => semesterSessions.filter((item) => !section || String(item.section) === String(section)), [semesterSessions, section]);
  const selectSubject = (value) => { setSubject(value); const selected = sectionSessions.find((item) => String(item.subject_name || item.subject) === String(value)); if (!selected) return; setClassSessionId(selected.id || ""); setDate(selected.date !== "-" ? selected.date : date); setStartTime(selected.start_time !== "-" ? selected.start_time : ""); setEndTime(selected.end_time !== "-" ? selected.end_time : ""); };
  const handleLoad = () => { if (!course || !semester || !section || !subject) { alert("Select course, semester, section and subject."); return; } onLoadStudents({ ...attendanceInfo, classSessionId, course, semester, section, subject, date, time: startTime, endTime }); };
  return <div className="attendance-header"><div className="header-top"><div className="header-title"><h2>Mark Attendance</h2><p>Select class details and load students</p></div><div className="today-badge"><FaCalendarAlt /><span>{date}</span></div></div><div className="header-grid"><SelectCard icon={<FaUniversity className="input-icon" />} label="Course" value={course} onChange={(value) => { setCourse(value); setSemester(""); setSection(""); setSubject(""); }} options={unique(sessions.map((item) => item.course_name || item.course))} /><SelectCard icon={<FaLayerGroup className="input-icon" />} label="Semester" value={semester} onChange={(value) => { setSemester(value); setSection(""); setSubject(""); }} options={unique(courseSessions.map((item) => item.semester))} /><SelectCard icon={<FaUsers className="input-icon" />} label="Section" value={section} onChange={(value) => { setSection(value); setSubject(""); }} options={unique(semesterSessions.map((item) => item.section))} /><SelectCard icon={<FaBook className="input-icon" />} label="Subject" value={subject} onChange={selectSubject} options={unique(sectionSessions.map((item) => item.subject_name || item.subject))} /></div><div className="header-grid second-grid"><InputCard icon={<FaCalendarAlt className="input-icon" />} label="Date" type="date" value={date} onChange={setDate} /><InputCard icon={<FaClock className="input-icon" />} label="Start Time" type="time" value={startTime} onChange={setStartTime} /><InputCard icon={<FaClock className="input-icon" />} label="End Time" type="time" value={endTime} onChange={setEndTime} /><div className="button-card"><button className="load-btn" onClick={handleLoad}>Load Students</button></div><div className="button-card"><button type="button" className="not-held-btn" onClick={onNotHeld}>Mark Not Held</button></div></div></div>;
}
function SelectCard({ icon, label, value, onChange, options }) { return <div className="input-card"><label>{label}</label><div className="input-group">{icon}<select value={value} onChange={(event) => onChange(event.target.value)}><option value="">Select {label}</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></div></div>; }
function InputCard({ icon, label, type, value, onChange }) { return <div className="input-card"><label>{label}</label><div className="input-group">{icon}<input type={type} value={value} onChange={(event) => onChange(event.target.value)} /></div></div>; }
export default AttendanceHeader;
