# Generated by Django 6.0.4 on 2026-07-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subject_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course_code',
            field=models.CharField(default='CS001', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='course_name',
            field=models.CharField(default='MCA', max_length=100),
            preserve_default=False,
        ),
    ]
