# Generated by Django 6.0.4 on 2026-07-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_subject_course_code_subject_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='course_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
    ]
