# Generated by Django 6.0.4 on 2026-07-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='course',
            field=models.CharField(default='MCA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classsession',
            name='section',
            field=models.CharField(default='A', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classsession',
            name='semester',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
