# Generated by Django 6.0.4 on 2026-07-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_no',
            field=models.CharField( max_length=30, null=True, blank=True), 
        ),
        migrations.AddField(
            model_name='user',
            name='contact_no',
            field=models.CharField(default='no description', max_length=15),
            preserve_default=False,
        ),
        
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        
        
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(default='MCA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, max_length=5),
        ),
       
        
        
        
    ]
