# Generated by Django 6.0.4 on 2026-07-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_contact_no_user_course_user_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_no',
            field=models.CharField(default='', max_length=30),
        ),
    ]
