# Generated by Django 6.0.4 on 2026-07-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_registration_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roll_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='batch',
            field=models.CharField(max_length=10),
        ),
    ]
