# Generated by Django 6.0.4 on 2026-07-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_role_remove_user_roll_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='batch',
            field=models.CharField(max_length=10),
        ),
    ]
