# Generated by Django 6.0.4 on 2026-07-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_no',
            field=models.CharField(max_length=10),
        ),
    ]
