# Generated by Django 6.0.4 on 2026-07-23 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_subject', '0001_initial'),
        ('subjects', '0002_alter_subject_subject_name'),
        ('users', '0007_user_department_user_role_alter_user_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultysubject',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_subjects', to='users.user'),
        ),
        migrations.AlterField(
            model_name='facultysubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_subjects', to='subjects.subject'),
        ),
    ]
