# Generated by Django 6.0.6 on 2026-07-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('batch', models.CharField(max_length=20)),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
